### ISSUE TITLE
Removing a friend I added to my trip also deleted my trip

### ISSUE THREAD

**Issue by cckole** [project-travel-mate/Travel-Mate#643] opened 2019-04-29 16:39 UTC
### Description 

When I added a friend to my trip list,and later removed him, my trip was deleted as well

### Expected behavior

I expected that only the friend I removed from the list should be deleted,not both the friend and my trip. 

### Note
I started my recording after adding trips to make the video short. The steps to add trips is simple. Following the steps below would definitely get you through.

***Steps to reproduce***

After signing up and entering the app

- Click on the three lines (menu) at the top left side of the app. 

- Click on my trip(It will display a blank page)

- locate a plus sign below by the left side and click on it.

- On the next page, fill every commands by entering your trip name,select trip date, and city, and click Add trip.

- Your trip will be added.

***After adding trip/trips (I started the recording from here)***

- After adding a trip, click on it. 

- On the shown page, enter friends name.(Note that friend name is an email address)

- Click on add new friend

- Go back and click delhi

- Click the drop down icon in front of "friends in this group".( you will see the list of your friends in that group with you)

- delete the friend. I deleted Martins as shown in the video. After the deletion, there would be a display of no network.

- Exit the app and go back to the trip page. You won't find the trip (Delhi or any city used in the trip). It deleted with the friend removed. 

### Reproducing the bug

https://youtu.be/GhCSb78Nm4w

### Device used

Tecno spark K7

Android 7.0

**Comment by valericaplesu** [comment] 2019-07-26 12:42
I cannot reproduce it on the latest code. @cckole can you give it a try? Thanks!

**Comment by Swati4star** [comment] 2019-08-14 14:56
@cckole Any response?

**Comment by prabhakar267** [comment] 2019-10-01 14:57
Closing this since it seems fixed!
@cckole Feel free to reopen if it isn't fixed

**Closed by prabhakar267** 2019-10-01 14:57 UTC
