### ISSUE TITLE
The activity multiplies in itself on refreshing

### ISSUE THREAD

**Issue by ShivangiSingh17** [project-travel-mate/Travel-Mate#678] opened 2019-05-27 17:28 UTC
### Description
On refreshing the page the activity multiplies itself as per the RefreshView happen.

### Steps to reproduce
Go to ```My Trips``` refresh your page.

### Screenshots
![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/43827236/58433218-bbe03a80-80d3-11e9-83d8-f8ac83e93fbe.gif)

### Would you like to work on this issue?
Yes

**Comment by Swati4star** [comment] 2019-07-20 14:24
@ShivangiSingh17 Are you willing to work on it now?

**Comment by ShivangiSingh17** [comment] 2019-07-20 15:32
I would like to continue in mere future. :)

**Comment by aman0408** [comment] 2019-10-04 19:17
Can I work on this issue?

**Comment by RMVIVEK55** [comment] 2019-10-05 05:47
I when  do you refresh data list and also list  clear (newly adding data clear the list)

**Comment by Swati4star** [comment] 2019-10-05 11:44
sure @aman0408

**Comment by aman0408** [comment] 2019-10-05 14:40
> sure @aman0408

I am unable to reproduce the error. I think it has been fixed already.

**Comment by Swati4star** [comment] 2019-10-06 05:45
I'll close this issue then :)

**Closed by Swati4star** 2019-10-06 05:45 UTC
Labels: bug, easy-pick, hacktoberfest, help wanted
