### ISSUE TITLE
Bug: Unable to open City Info for cities on the right side of the CityFragment

### ISSUE THREAD

**Issue by aman0408** [project-travel-mate/Travel-Mate#734] opened 2019-10-06 20:08 UTC
### **Describe the bug.**
Can't view information of cities on the right of the list eg. Bangalore,Chennai, Jaipur etc.
### **Steps to reproduce.**

- Launch the app.

- Click on a city on the right

- And note the bug (opened info is of the left city

### **Expected behavior**
It is expected that the info of the city that has been touched should be opened.

**Comment by aman0408** [comment] 2019-10-06 20:54
Shall I work on this issue?

**Comment by prabhakar267** [comment] 2019-10-06 21:14
Please make sure you only claim one issue at a time, if you have nothing else, go ahead.

**Comment by aman0408** [comment] 2019-10-06 21:15
I have already created a PR for the issue that was assigned to me so I got nothing to do. I'll work on this.

**Comment by aman0408** [comment] 2019-10-07 16:28
Can someone give me a summary of what's happening in the CityAdapter and the BaseFlipAdapter classes? I'm having difficulty understanding those.

**Comment by prabhakar267** [comment] 2019-10-07 22:23
@aayushinigam @amy6 @brijeshshah13 You guys have worked on `CityAdapter`, can you help @aman0408 out.

**Comment by aman0408** [comment] 2019-10-07 22:29
I just need a jist of what each function does and returns. Also specifically need to know which function returns the view on click.

**Comment by aman0408** [comment] 2019-10-08 11:20
@prabhakar267 if there's noone to explain, can I reimplement the home screen using a gridlayout having a single independent adapter instead of using multiple adapters?

**Comment by prabhakar267** [comment] 2019-10-08 14:16
@aman0408 Swati is a bit busy these days, you can pick up some other issue meanwhile. As soon as she will be free, she can explain you what is happening in the code.

**Comment by aman0408** [comment] 2019-10-08 14:20
Alright!

**Comment by Swati4star** [comment] 2019-10-16 16:57
Duplicate of https://github.com/project-travel-mate/Travel-Mate/issues/750
Closing this one. #750 is in progress.

**Closed by Swati4star** 2019-10-16 16:57 UTC
Labels: bug, hacktoberfest, help wanted
