### ISSUE TITLE
[ Travel Mate version 5.4.0 ]  In the Hotels booking call and location button are not working 

### ISSUE THREAD

**Issue by XAMIR555** [project-travel-mate/Travel-Mate#627] opened 2019-04-24 10:21 UTC
#### Project Information
* Repository    :  https://github.com/project-travel-mate/Travel-Mate
* Project Name  :  Travel Mate
* Publisher     :   Swati Garg

#### Expected behavior

I expected that in the Hotels booking when I click on the call button  the hotel's contact should be shown and when I click on the location button the hotel,s location show in google map 

#### Actual behavior

after opening the Hotels booking tab when  I click on the call button and location button the both ( call and location )  button are not working properly. you can see in bug video properly 

#### How to reproduce
* [Download ](https://play.google.com/store/apps/details?id=io.github.project_travel_mate)and open the application
* click on the  ( menu on the top left corner )
* click on ( travel ) 
* click on ( HOTEL BOOKING )
* select the ( city Delhi )
* click ( on Tab for more Details )
* now click on ( call icon and location icon ) 
* Note the Bug
* Browser/App version:   5.4.0
* Operating system:  8.0.0 

#### Recording Of The Bug
https://youtu.be/hzfI1hujzDQ
#### GitHub Account
https://github.com/XAMIR555

# Logcat
<pre><code>04-21 02:30:48.457  5228  5228 E AndroidRuntime: FATAL EXCEPTION: main
04-21 02:30:48.457  5228  5228 E AndroidRuntime: Process: com.huawei.autoinstallapkfrommcc, PID: 5228
04-21 02:30:48.457  5228  5228 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.huawei.autoinstallapkfrommcc.InstallAPKReceiver: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3705)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.ActivityThread.-wrap18(Unknown Source:0)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1979)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:108)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7425)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:312)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at com.huawei.autoinstallapkfrommcc.InstallAPKReceiver.onReceive(InstallAPKReceiver.java:42)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3695)
</code></pre>

**Comment by OlgaMorales** [comment] 2019-04-25 22:43
hi @Swati4star i'd like to help u with this issue , however I'm facing the next trouble , when i try to create one account i see a message which says "invalid user name or password" I've checked if passwords are equal and they are , so what could be the error?

**Comment by Swati4star** [comment] 2019-04-27 10:15
the passwords need to be alphanumeric with one special character. Can you check if these conditions are satisfied.

**Comment by OlgaMorales** [comment] 2019-04-27 12:31
Length? Whatever ?

**Comment by Swati4star** [comment] 2019-04-27 15:53
https://github.com/project-travel-mate/Travel-Mate/blob/master/Android/app/src/main/java/io/github/project_travel_mate/login/LoginActivity.java#L434

Length >= 8

**Comment by OlgaMorales** [comment] 2019-04-28 01:15
I guess , It's necessary to put a google maps key ,isn't it ? if yes, where can I find it's reference?

**Comment by OlgaMorales** [comment] 2019-05-07 18:27
hi @Swati4star when I am in  HOTEL BOOKING and type Delhi , I just can see one image which says: Searching Network , We're sorry we could not connect, I don't know Why I can't reproduce the issue, help me please. I think what is expected is that when I type the name of the City, something should be shown but I am not getting any result.

**Comment by OlgaMorales** [comment] 2019-05-07 18:39
![picturescreen](https://user-images.githubusercontent.com/48235441/57324470-78df0880-70cd-11e9-9eb2-220f86c912cb.png)

**Comment by prabhakar267** [comment] 2019-10-02 19:08
Closing this since it seems fixed!
@XAMIR555  Feel free to reopen if it isn't fixed

**Closed by prabhakar267** 2019-10-02 19:08 UTC
