### ISSUE TITLE
[ Travel Mate version 5.4.0 ]  My Trips automatically become  Add  when I refresh the page

### ISSUE THREAD

**Issue by XAMIR555** [project-travel-mate/Travel-Mate#625] opened 2019-04-24 08:57 UTC
#### Project Information
* Repository    :  https://github.com/project-travel-mate/Travel-Mate
* Project Name  :  Travel Mate
* Publisher     :  Swati Garg

#### Expected behavior

I expected that when I refresh  my trips page  My trip should not be Add automatically 

#### Actual behavior

after opening the application when I create my Trips and refresh the page My Trips automatically add in my trips page. you can see in bug video properly 

#### How to reproduce
* [Download ](https://play.google.com/store/apps/details?id=io.github.project_travel_mate)and open the application
* click on my Trips 
* add your new trips 
*  refresh the My tripe page 
* Note the Bug
* Browser/App version:   5.4.0
* Operating system:  8.0.0 

#### Recording Of The Bug
![final_5cc6c0d069cff900136c3287_273144.gif](https://ipfs.busy.org/ipfs/QmUXCBPW5xNr49mERBLL3kWRJwT425pfggFXPwEUwyiYj6)
#### GitHub Account
https://github.com/XAMIR555

**Comment by aman0408** [comment] 2019-10-06 08:22
@Swati4star this is similar to #678 which you closed and again I'm unable to reproduce this. Someone else please comfirm if it really exists

**Comment by prabhakar267** [comment] 2019-10-06 08:55
Closing this. @XAMIR555 please reopen if issue is not fixed

**Closed by prabhakar267** 2019-10-06 08:55 UTC
Labels: bug, easy-pick, hacktoberfest, help wanted
