### ISSUE TITLE
App crashed when I accessed the shopping feature and pressed the white background

### ISSUE THREAD

**Issue by cckole** [project-travel-mate/Travel-Mate#660] opened 2019-05-12 23:13 UTC
### App info
Travel mate v.5.5.0

## Descriptions

On the destination page, I clicked on a city and access the shopping feature, but the app crashed when I mistakenly press  the white background.

### Expected behavior
My expectation was to use the page freely without the fear of the app crashing whenever I mistakenly press  or touch the white background.

### Steps to reproduce

After login into the app, 

- Click on the menu by the top left side

- Click on destination

- Select any city and click on `shopping`

- press any part of the white background housing the map features and note the crash.

### Reproducing the behavior
https://youtu.be/gG9JxGTMNlI

### Device used
Techno spark K7
Android 7.0
### Logcat

```05-15 21:30:05.227  9156  9156 E AndroidRuntime: FATAL EXCEPTION: main
05-15 21:30:05.227  9156  9156 E AndroidRuntime: Process: io.github.project_travel_mate, PID: 9156
05-15 21:30:05.227  9156  9156 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.project_travel_mate/io.github.project_travel_mate.travel.ListViewRealTimeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.osmdroid.views.MapView.getContext()' on a null object reference
05-15 21:30:05.227  9156  9156 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
05-15 21:30:05.227  9156  9156 E AndroidRuntime: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
05-15 21:30:05.227  9156  9156 E AndroidRuntime: at android.app.ActivityThread.-wrap12(ActivityThread.java)
05-15 21:30:05.227  9156  9156 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
05-15 21:30:05.227  9156  9156 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:110)
05-15 21:30:05.227  9156  9156 E AndroidRuntime: at android.os.Looper.loop(Looper.java:203)
05-15 21:30:05.227  9156  9156 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6251)
05-15 21:30:05.227  9156  9156 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
05-15 21:30:05.227  9156  9156 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
05-15 21:30:05.227  9156  9156 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
05-15 21:30:05.227  9156  9156 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.osmdroid.views.MapView.getContext()' on a null object reference
05-15 21:30:05.227  9156  9156 E AndroidRuntime: at org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.<init>(MyLocationNewOverlay.java:100)
05-15 21:30:05.227  9156  9156 E AndroidRuntime: at utils.GPSTracker.displayLocationRequest(GPSTracker.java:154)
05-15 21:30:05.227  9156  9156 E AndroidRuntime: at io.github.project_travel_mate.travel.ListViewRealTimeActivity.onCreate(ListViewRealTimeActivity.java:55)
05-15 21:30:05.227  9156  9156 E AndroidRuntime: at android.app.Activity.performCreate(Activity.java:6670)
05-15 21:30:05.227  9156  9156 E AndroidRuntime: at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
05-15 21:30:05.227  9156  9156 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
05-15 21:30:05.227  9156  9156 E AndroidRuntime: ... 9 more```

**Comment by valericaplesu** [comment] 2019-07-26 12:34
I cannot reproduce it using the latest code. @cckole can you please give it a try? Thanks!

**Comment by Swati4star** [comment] 2019-08-04 16:04
@cckole Any response here?

**Comment by prabhakar267** [comment] 2019-10-01 15:22
Closing this since it seems fixed!
@cckole Feel free to reopen if it isn't fixed

**Closed by prabhakar267** 2019-10-01 15:22 UTC
