### ISSUE TITLE
Bug: Analog time doesn't correspond with digital time 

### ISSUE THREAD

**Issue by darewealth** [project-travel-mate/Travel-Mate#669] opened 2019-05-19 11:42 UTC
### Describe the bug.

The analog time doesn't correspond with digital time in some countries. E..g America /Anchorage 

### Steps to reproduce.
* Launch the app.

* Click on the menu and go to utilities 

* Click on word clock  

*  Then select  country to "America/Anchorage"

* And note the bug

### Expected behavior 

I expected that the analog and digital time should be the same. 

### Screen recording
https://youtu.be/BaY4AQQBw7s

### Devices and Versions):)
* Device: [Gionee]

* Version [7.0]

* App version [5.5.0]

**Comment by prithvish-doshi-17** [comment] 2019-05-22 05:55
I would like to work on the issue. Please assign it to me

**Comment by HeinKhantZaw** [comment] 2019-10-03 06:01
@prithvish-doshi-17 Is this issue solved?
If not, I wanna work on this issue.

**Comment by prabhakar267** [comment] 2019-10-03 06:14
@HeinKhantZaw Go ahead!

**Comment by aman0408** [comment] 2019-10-05 15:59
Can I also work on this?

**Comment by Swati4star** [comment] 2019-10-08 09:05
@HeinKhantZaw Are you working on this issue?

**Comment by HeinKhantZaw** [comment] 2019-10-08 14:39
Yes @Swati4star  I am working but the issue is still not solved.

**Comment by aman0408** [comment] 2019-10-08 15:27
I was able to partial fix the issue. Everything works fine when the user initially has 12 hour clock enabled. If the format is changed to 24 hour, time is displayed correctly without the seconds (only hours and minutes are shown). 

Basically hours and minutes are always displayed correctly. Seconds are displayed only when the user has 12 hour clock enabled.

**Comment by HeinKhantZaw** [comment] 2019-10-11 18:34
I have fixed the issue @Swati4star

**Comment by prabhakar267** [comment] 2019-10-21 19:48
Closed in #747

**Closed by prabhakar267** 2019-10-21 19:48 UTC
Labels: bug, hacktoberfest, help wanted
